<?php

namespace Database\Seeders;

use App\Models\Plan;
use Illuminate\Database\Seeder;

class PlanSeeder extends Seeder
{
    public function run(): void
    {
        $plans = [
            [
                'name' => 'Starter',
                'slug' => 'starter',
                'description' => 'Idéal pour les PME et freelances qui démarrent',
                'price_monthly' => 0,
                'price_yearly' => 0,
                'currency' => 'XOF',
                'trial_days' => 0,
                'max_users' => 1,
                'max_customers' => 50,
                'max_invoices_per_month' => 20,
                'max_products' => 50,
                'max_quotes_per_month' => 10,
                'max_storage_mb' => 100,
                'feature_quotes' => true,
                'feature_expenses' => false,
                'feature_reports' => false,
                'feature_api_access' => false,
                'feature_multi_currency' => false,
                'feature_custom_templates' => false,
                'feature_reminders' => false,
                'feature_stock_management' => false,
                'feature_purchase_orders' => false,
                'feature_priority_support' => false,
                'feature_white_label' => false,
                'features_list' => [
                    'Gestion clients',
                    'Gestion produits',
                    'Création de devis',
                    'Création de factures simples',
                    'Tableau de bord basique',
                    'Gestion des paiements',
                    '1 utilisateur',
                    '50 clients max',
                    '20 factures/mois',
                    'Support email',
                ],
                'sort_order' => 1,
                'is_popular' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Professional',
                'slug' => 'professional',
                'description' => 'Pour les petites PME en croissance',
                'price_monthly' => 15000,
                'price_yearly' => 144000,
                'currency' => 'XOF',
                'trial_days' => 14,
                'max_users' => 3,
                'max_customers' => -1,
                'max_invoices_per_month' => -1,
                'max_products' => -1,
                'max_quotes_per_month' => -1,
                'max_storage_mb' => 2000,
                'feature_quotes' => true,
                'feature_expenses' => true,
                'feature_reports' => true,
                'feature_api_access' => false,
                'feature_multi_currency' => false,
                'feature_custom_templates' => true,
                'feature_reminders' => true,
                'feature_stock_management' => true,
                'feature_purchase_orders' => true,
                'feature_priority_support' => false,
                'feature_white_label' => false,
                'features_list' => [
                    'Tout le plan Starter',
                    'Clients illimités',
                    'Factures illimitées',
                    'Gestion fournisseurs',
                    'Gestion des dépenses',
                    'Inventaire simple',
                    'Bons de commande',
                    'Rapports financiers',
                    '3 utilisateurs',
                    'Export Excel / PDF',
                    'Notifications',
                ],
                'sort_order' => 2,
                'is_popular' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Business',
                'slug' => 'business',
                'description' => 'Pour les PME structurées',
                'price_monthly' => 35000,
                'price_yearly' => 336000,
                'currency' => 'XOF',
                'trial_days' => 14,
                'max_users' => 10,
                'max_customers' => -1,
                'max_invoices_per_month' => -1,
                'max_products' => -1,
                'max_quotes_per_month' => -1,
                'max_storage_mb' => 10000,
                'feature_quotes' => true,
                'feature_expenses' => true,
                'feature_reports' => true,
                'feature_api_access' => true,
                'feature_multi_currency' => true,
                'feature_custom_templates' => true,
                'feature_reminders' => true,
                'feature_stock_management' => true,
                'feature_purchase_orders' => true,
                'feature_priority_support' => true,
                'feature_white_label' => false,
                'features_list' => [
                    'Tout le plan Professional',
                    'Gestion multi-entrepôts',
                    'Gestion stocks avancée',
                    'Rapports avancés',
                    'Dashboard personnalisé',
                    'Gestion équipes (10 utilisateurs)',
                    'API',
                    'Intégrations (WhatsApp, paiement)',
                    'Facturation automatique',
                    'Historique des actions',
                ],
                'sort_order' => 3,
                'is_popular' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Enterprise',
                'slug' => 'enterprise',
                'description' => 'Solution complète pour les grandes entreprises',
                'price_monthly' => 100000,
                'price_yearly' => 960000,
                'currency' => 'XOF',
                'trial_days' => 14,
                'max_users' => -1,
                'max_customers' => -1,
                'max_invoices_per_month' => -1,
                'max_products' => -1,
                'max_quotes_per_month' => -1,
                'max_storage_mb' => -1,
                'feature_quotes' => true,
                'feature_expenses' => true,
                'feature_reports' => true,
                'feature_api_access' => true,
                'feature_multi_currency' => true,
                'feature_custom_templates' => true,
                'feature_reminders' => true,
                'feature_stock_management' => true,
                'feature_purchase_orders' => true,
                'feature_priority_support' => true,
                'feature_white_label' => true,
                'features_list' => [
                    'Tout le plan Business',
                    'Utilisateurs illimités',
                    'Multi entreprises',
                    'Modules personnalisés',
                    'Intégrations ERP externes',
                    'Support prioritaire',
                    'Formation',
                    'Hébergement dédié',
                    'Sécurité avancée',
                    'Sauvegardes avancées',
                ],
                'sort_order' => 4,
                'is_popular' => false,
                'is_active' => true,
            ],
        ];

        foreach ($plans as $plan) {
            Plan::updateOrCreate(['slug' => $plan['slug']], $plan);
        }
    }
}
